sonar.projectKey=proyecto_gestion_pedidos
sonar.projectName=Proyecto Gestion Pedidos
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java

sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/jacoco-report/jacoco.xml
sonar.token=sqa_2338d272bd29485386d43c29c1c2dc511e71c7c2